@Library('pipeline-library-demo')_
pipeline {
    agent any

    environment {
            AWS_ECR_LOGIN='true'
    }
    stages {
        stage ('checkout') {
            steps {
                echo 'Checking out code from git repo'
                checkout scm
            }
        }

        stage ('clean') {
            steps {
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle clean"
            }
        }

        stage ('compile') {
            steps {
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle compileJava"
            }
        }

        stage ('Build') {
            steps {
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle build -x test -i"
            }
        }
        
        stage ('test') {
            sayHello 'test'
            steps {
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle test"
            }                
        }
    }
}
