pipeline {
    agent any

    environment {
            AWS_ECR_LOGIN='true'
    }
    stages {
        stage ('checkout') {
            steps {
                echo 'Checking out code from git repo'
                checkout scm
            }
        }

        stage ('clean') {
            steps {
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle clean"
            }
        }

        stage ('compile') {
            steps {
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle compileJava"
            }
        }

        stage ('Build') {
            steps {
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle build -x test -i"
            }
        }
        
        stage ('test') {
            steps {
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle test"
            }
        }
        
         stage ('Sonar Analysis') {
            steps {
                script {
                if (env.GIT_BRANCH == 'develop') {
                    sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle sonar -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_PASSWORD}"
                }
                else if (env.CHANGE_ID){
                echo 'This is a PR build. Running sonnar preview analysis'
                sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle sonar -Dsonar.github.pullRequest=${env.CHANGE_ID} -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_PASSWORD} -Dsonar.analysis.mode=preview -Dsonar.github.oauth=68eb8d979fe364931397bf39faa671159e5926ec -Dsonar.github.repository=${env.CUSTOM_SONAR_REPO_NAME} -i"
                }else{
                    echo 'This is a branch build.'
                    sh "./sonarqube-scanner-gradle/gradlew -b ./sonarqube-scanner-gradle/build.gradle sonar -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_PASSWORD} -Dsonar.github.repository=${env.CUSTOM_SONAR_REPO_NAME} -Dsonar.branch=${env.GIT_BRANCH} -i"
                }
                
        }
    }
