/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    
    public void test1(){
	System.out.println("Hello");
        System.out.println("Hello");
    }

    public void test2(){
        System.out.println("Hello");
        System.out.println("Hello");
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
